basePath: /
host: localhost:8084
info:
  contact: {}
  description: Payments processing service
  title: Seraph Payments Service
  version: "1.0"
paths:
  /payments/health:
    get:
      description: Returns the health status of the payments service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - payments
swagger: "2.0"
